---
title: "ESM 244 Winter 2022 - Lab 7 Spatial Data - Part 1"
author: "Kiera Matiska"
date: "2/17/2022"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(broom)

library(sf) # sf = simple features
library(tmap)
```

# Part 1: Spatial data wrangling, visualization

## A. California county outlines (polygons)

```{r}
ca_counties_sf <- read_sf(here("data/ca_counties/CA_Counties_TIGER2016.shp"))

ca_subset_sf <- ca_counties_sf %>% 
  janitor::clean_names() %>% 
  select(county_name = name, land_area = aland) # includes a geometry section because it came from a .shp file

# ca_counties_df <- ca_counties_sf %>% 
#   as.data.frame() %>% 
#   select(-geometry)
# only use this if you need to make a data frame
```

### Examine and set CRS

```{r}
ca_subset_sf %>% st_crs() # EGS 84 / Pseudo-Mercator

ca_subset_sf %>% raster::crs()
```

```{r}
ggplot(data = ca_subset_sf) +
  geom_sf(aes(fill = land_area), color = "white", size = 0.1) + # makes a map
  theme_void() + # removes the plot and x and y axies
  scale_fill_gradientn(colors = c("cyan", "blue", "purple"))
```

## B. Invasive Red sesbania Records (spatial points)

```{r}
sesbania_sf <- read_sf(here("data/red_sesbania", "ds80.shp")) %>% 
  janitor::clean_names()

# check CRS:
sesbania_sf %>% st_crs() # Custom
sesbania_sf %>% raster::crs()

# if you know the EPSG
sesbania_3857_sf <- st_transform(sesbania_sf, 3857)

#if you don't know EPSG
sesbania_3857_2_sf <- st_transform(sesbania_sf, st_crs(ca_subset_sf))

# check new one
sesbania_3857_sf %>% st_crs()
```

### Plot them together!

```{r}
# can use ggplotly to click attributes

ggplot() +
  geom_sf(data = ca_subset_sf) +
  geom_sf(data = sesbania_3857_sf, size = 1, color = "red")
```

### Wrangle to find sesbania observations per county

```{r}
ca_sesb_sf <- ca_subset_sf %>% 
  st_join(sesbania_3857_sf)

head(ca_sesb_sf)
```

```{r}
sesb_counts_sf <- ca_sesb_sf %>% 
  group_by(county_name) %>% 
  summarize(n_records = sum(!is.na(id))) # counts the number of sesbania in each county without dropping the counties that do not have any

head(sesb_counts_sf)
```

```{r}
ggplot(data = sesb_counts_sf) +
  geom_sf(aes(fill = n_records), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("lightgrey", "orange", "red")) +
  theme_minimal() +
  labs(fill = "Number of S. punicea Records")
```

### Filter to just occurrences in Solano County

```{r}
# subset sesbonia based on Solano County
solano_sesb_sf <- sesbania_3857_sf %>% 
  filter(county == "Solano")

# subset counties based on Solano
solano_sf <- ca_subset_sf %>% 
  filter(county_name == "Solano")

ggplot() +
  geom_sf(data = solano_sf) +
  geom_sf(data = solano_sesb_sf, color = "red")
```

```{r}
tmap_mode(mode = "view") # creates an interactive map

tm_shape(ca_subset_sf) +
  tm_fill("land_area", palette = "BuGn") + # BuGn is a blue green palette fill
  tm_borders(col = "black") +
tm_shape(sesbania_3857_sf) +
  tm_dots()
```
